name: hello_world
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.0
  cupertino_icons: ^0.1.2
#  firebase_auth: ^0.14.0
#  ^0.9.0
  firebase_database: ^3.1.0
  carousel_slider: ^1.3.0
  cloud_firestore: ^0.12.9+4
  firebase_core: ^0.4.0
  flutter_slidable: ^0.4.6

  loading: ^1.0.1
  uuid: 2.0.1
  font_awesome_flutter: ^8.5.0
  charts_flutter: ^0.8.1
  fluttertoast: ^3.1.3
  flutter_icons: ^0.3.1
  google_sign_in: ^4.0.14
  firebase_auth: ^0.15.3
  auto_size_text: ^2.0.2



  provider: ^3.1.0+1
  get_it: ^1.0.3+2
  loading_animations: "^2.0.0"





  #login2

  image_picker:  ^0.6.0+9
  shared_preferences: ^0.5.3+1
  firebase_storage: ^3.0.1
  intl: ^0.15.8
  diacritic: ^0.1.1
  sentry: ^2.2.0
  image_cropper: ^1.0.2
  contacts_service: ^0.2.4
  permission_handler: ^3.0.0
  share: ^0.6.1
  scoped_model: ^1.0.1
  local_auth: ^0.5.2+3
  avatar_glow:


  flutter_launcher_icons: "^0.7.3"





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/flutterwithlogo.png
    - assets/images/1.png
    - assets/images/mountains.jpg
    - data/
    - assets/images/launch.png
    - assets/images/launch1.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch.png"






fonts:
- family: icomoon
  fonts:
  - asset: assets/fonts/IcoMoon.ttf

  - family: Raleway
  - asset: font/Raleway-Regular.ttf
  - asset: font/Raleway-Italic.ttf
  style: italic






  
